---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: digio-teste
    provider: fabric8
    version: 0.0.6-SNAPSHOT
    group: br.com.digio
  name: digio-teste
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: digio-teste
    provider: fabric8
    group: br.com.digio
  type: LoadBalancer
