---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digio-teste
    provider: fabric8
    version: 0.0.6-SNAPSHOT
    group: br.com.digio
  name: digio-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digio-teste
      provider: fabric8
      group: br.com.digio
  template:
    metadata:
      labels:
        app: digio-teste
        provider: fabric8
        version: 0.0.6-SNAPSHOT
        group: br.com.digio
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPRING_PROFILES_ACTIVE
          value: develop
        image: diegolirio/digio-teste:0.0.6-SNAPSHOT
        imagePullPolicy: Always
        name: spring-boot-starter-parent
        securityContext:
          privileged: false
