version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - digio-teste
  jeager:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  digio-teste:
    image: diegolirio/digio_teste:0.0.1-SNAPSHOT
    container_name: digio-teste
    #restart: always
    ports:
      - 8080:8080