---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        expose: "true"
        app: digio-teste
        provider: fabric8
        version: 0.0.5-SNAPSHOT
        group: br.com.digio
      name: digio-teste
    spec:
      ports:
        - nodePort: 30080
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: digio-teste
        provider: fabric8
        group: br.com.digio
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: digio-teste
        provider: fabric8
        version: 0.0.5-SNAPSHOT
        group: br.com.digio
      name: digio-teste
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: digio-teste
          provider: fabric8
          group: br.com.digio
      template:
        metadata:
          labels:
            app: digio-teste
            provider: fabric8
            version: 0.0.5-SNAPSHOT
            group: br.com.digio
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SPRING_PROFILES_ACTIVE
                  value: default
                - name: ENV
                  value: dev
              image: diegolirio/digio-teste:0.0.5-SNAPSHOT
              imagePullPolicy: Always
              name: spring-boot-starter-parent
              securityContext:
                privileged: false
              livenessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                initialDelaySeconds: 25
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /actuator/health
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 3       
              ports:
                - containerPort: 8080
              resources:
                requets: 
                  memory: 128Mi
                  cpu: 300m
                limits:
                  memory: 256Mi
                  cpu: 400m


