---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        expose: "true"
        app: digio-teste
        provider: fabric8
        version: 0.0.1-SNAPSHOT
        group: br.com.digio
      name: digio_teste
    spec:
      ports:
        - nodePort: 30080
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: digio_teste
        provider: fabric8
        group: br.com.digio
      type: LoadBalancer
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        app: digio_teste
        provider: fabric8
        version: 0.0.1-SNAPSHOT
        group: br.com.digio
      name: digio_teste
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: digio_teste
          provider: fabric8
          group: br.com.digio
      template:
        metadata:
          labels:
            app: digio_teste
            provider: fabric8
            version: 0.0.1-SNAPSHOT
            group: br.com.digio
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SPRING_PROFILES_ACTIVE
                  value: default
              image: diegolirio/digio_teste:0.0.1-SNAPSHOT
              imagePullPolicy: Always
              name: spring-boot-starter-parent
              securityContext:
                privileged: false