version: '3'
services:
  jeager:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  foodtruck:
    image: diegolirio/digio_teste:0.0.1-SNAPSHOT
    container_name: digio_teste
    #restart: always
    ports:
      - 8080:8080
    #environment:
    #  - SERVICE_CLIENTE_URL=cliente:8081
    #  - SERVICE_PRODUTO_URL=produto:8080