spring:
  application:
    name: @project.artifactId@
    version: @project.version@

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,mongodb,configprops
---
spring:
  profiles: default, local
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://digio:digio123@ds119738.mlab.com:19738/digio-db?retryWrites=false}
opentracing:
  jaeger:
    log-spans: false
    enable-b3-propagation: false

server:
  port: 8081

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

services:
  conta:
    url: http://localhost:8080
---
spring:
  profiles: develop
  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://digio:digio123@ds119738.mlab.com:19738/digio-db?retryWrites=false}

opentracing:
  jaeger:
    log-spans: false
    #enable-b3-propagation: true
    #udp-sender:
    #  host: jaeger
    #  port: 6831

services:
  conta:
    url: ${SERVICES_CONTA_URL:http://conta:8080}



