spring:
  application:
    name: digio-teste

  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://digio:digio123@ds119738.mlab.com:19738/digio-db?retryWrites=false}

opentracing:
  jaeger:
    log-spans: true
    enable-b3-propagation: true

---

spring:
  profiles: develop
  application:
    name: digio_teste

  data:
    mongodb:
      uri: ${MONGO_DB_URL:mongodb://digio:digio123@ds119738.mlab.com:19738/digio-db?retryWrites=false}

opentracing:
  jaeger:
    #log-spans: false
    #enable-b3-propagation: true
    udp-sender:
      host: jaeger
      port: 6831



