# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"app":"prometheus","chart":"prometheus","heritage":"Tiller","release":"istio"},"name":"prometheus","namespace":"istio-system"},"spec":{"ports":[{"name":"http-prometheus","port":9090,"protocol":"TCP"}],"selector":{"app":"prometheus"}}}
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-09-13T01:27:39Z"
  labels:
    app: prometheus
    chart: prometheus
    heritage: Tiller
    release: istio
  name: prometheus
  namespace: istio-system
  resourceVersion: "24234"
  selfLink: /api/v1/namespaces/istio-system/services/prometheus
  uid: ff36c276-39d3-4c62-b0fd-920c7946db25
spec:
  clusterIP: 10.152.183.141
  externalTrafficPolicy: Cluster
  ports:
  - name: http-prometheus
    nodePort: 30090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
