apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digio-teste
    provider: fabric8
    version: 0.0.27-SNAPSHOT
    group: br.com.digio
    canary: "false"
  name: digio-teste-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digio-teste
      provider: fabric8
      group: br.com.digio
  template: 
    metadata:
      labels:
        app: digio-teste
        provider: fabric8
        version: 0.0.27-SNAPSHOT
        group: br.com.digio
        canary: "false"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'          
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPRING_PROFILES_ACTIVE
          value: develop
        - name: SERVICES_CONTA_URL
          value: http://10.152.183.200:8080
        image: diegolirio/digio-teste:0.0.27-SNAPSHOT
        imagePullPolicy: Always
        name: spring-boot-starter-parent
        securityContext:
          privileged: false