AWSTemplateFormatVersion: "2010-09-09"
Description: "Pipeline APP EKS | Versao 1.1.0"

Parameters:

  PipelineVersion:
    Description: Versao de utilizacao da pipeline.
    Type:  String
    Default: '1.1.0'

  FeatureName:
    Description: Nome do produto, necessario refletir a taxonomia utilizada para a Cloud Publica AWS Itau.
    Type:  String
    AllowedPattern: "[a-z]*"
    
  MicroServiceName:
    Description: Nome do microsservico ou aplicacao, necessario refletir a taxonomia utilizada para a Cloud Publica AWS Itau.
    Type:  String
    AllowedPattern: "[a-z]*"

  Runtime:
    Description: Runtime do codigo da aplicacao.
    Type: String
    Default: 'maven: openjdk8'
    AllowedValues:
      - 'maven: openjdk8'
      - 'maven: openjdk11'
      - 'gradle: openjdk8'
      - 'gradle: openjdk11'
      - 'dotnet: 2.1'
      #- 'dotnet: 2.2' # versao 2.2 nao suportada pelo fortify
      - 'python: 3.7'
      - 'nodejs: 12'
     
  RuntimeEKS:
    Description: Runtime do EKS.
    Type: String
    Default: '1.15'
    AllowedValues:
      - '1.15'
      - '1.16'
      - '1.17'

  BranchName:
    Description: Nome da branch, necessario escolher entre "master" ou "develop".
    Type:  String
    Default: 'master'

  DevSecOpsAccount:
    Description: Numero da conta core da squad DevSecOps.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Accounts/DevSecOps'

  DevToolsAccount:
    Description: Numero da conta DevTools do produto.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Accounts/DevTools'

  DevAccount:
    Description: Numero da conta de Desenvolvimento do produto.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Accounts/Dev'

  HomologAccount:
    Description: Numero da conta de Homologacao do produto.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Accounts/Homolog'

  ProdAccount:
    Description: Numero da conta de Producao do produto.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Accounts/Prod'

  KMSKeyArn:
    Description: Nome do recurso na AWS para a chave KMS da pipeline.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Shared/KMSKeyArn'

  TokenAqua:
    Description: Token para o estagio Aqua na pipeline.
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/Shared/TokenAqua'

  VPCID:
    Description: Numero de identificacao da VPC (Virtual Private Cloud) da conta.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Networking/VPCID'

  BuildCustomizado:
    Description: Escolha entre utilizar seu proprio arquivo "buildspec" ou arquivo "buildspec" padrao da pipeline.
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    
  NormalizaDiretorios:
    Description: Selecione "true" se deseja normalizar os diretorios do seu repositorio
    Type: String
    Default: 'false'
    AllowedValues: 
      - 'true'
      - 'false'

  PrivateSubnetOne:
    Description: Numero de identificacao da primeira sub-rede Privada da conta.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Networking/PrivateSubnetOne'

  PrivateSubnetTwo:
    Description: Numero de identificacao da segunda sub-rede Privada da conta.
    Type:  'AWS::SSM::Parameter::Value<String>'
    Default: '/Networking/PrivateSubnetTwo'

  AprovadorPO:
    Description: E-mail do responsavel pelo produto (PO - Product Owner).
    Type:  String
    Default: '@itau-unibanco.com.br'

  AprovadorBO:
    Description: E-mail do responsavel por parte de negocios pelo produto (BO - Bussiness Owner).
    Type:  String
    Default: '@itau-unibanco.com.br'

  NamespaceGitLab:
    Description: Nome do espaco do GitLab Corporativo do produto (Ex. Sigla).
    Type:  String
    Default: '<namespace>'

  RepositorioGitLab:
    Description: Nome do repositorio do Gitlab Corporativo do microsservico ou aplicacao.
    Type:  String
    Default: '<repositorio>'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "REQUIRED FIELDS"
        Parameters:
          - FeatureName
          - MicroServiceName
          - Runtime
          - NamespaceGitLab
          - RepositorioGitLab
          - AprovadorBO
          - AprovadorPO
          - BuildCustomizado
          - BranchName
      -
        Label:
          default: "DO NOT MAKE CHANGES ON THE PARAMETERS BELOW"
        Parameters:
          - DevSecOpsAccount
          - DevToolsAccount
          - ProdAccount
          - HomologAccount
          - DevAccount
          - PrivateSubnetOne
          - PrivateSubnetTwo
          - VPCID
          - KMSKeyArn
          - TokenAqua

Conditions:
  BranchMaster: !Equals [ "master", !Ref BranchName ]
  BranchDevelop: !Equals [ "develop", !Ref BranchName ]
  IsBuildCustom: !Equals [ !Ref BuildCustomizado, true ]
  NormalizaDiretorios: !Equals [ !Ref NormalizaDiretorios, true ]
  IsNode12 : !Equals [ "nodejs: 12", !Ref Runtime ]
  IsOpenjdk11: !Or [!Equals ["maven: openjdk11", !Ref Runtime], !Equals ["gradle: openjdk11", !Ref Runtime]]

############################## RESOURCES
Resources:

############################## CodePipeline (Estrutura da Pipeline)
  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', !Ref 'BranchName']]
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/DevOpsRole'
      ArtifactStore:
        Type: S3
        Location: !Sub '${AWS::AccountId}-artefatos'
        EncryptionKey:
          Id: !Ref KMSKeyArn
          Type: KMS

      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeCommit
              Configuration:
                RepositoryName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName']]
                BranchName: !Ref BranchName
              OutputArtifacts:
                - Name: Appl
              RunOrder: 1

            - Name: SharedLibrary
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: "1"
              Configuration:
                BranchName: release-3.1.x
                RepositoryName: pipelineaws-sharedlibrary
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: Libs
              RunOrder: 1
              RoleArn: !Sub "arn:aws:iam::${DevSecOpsAccount}:role/DevOpsRole"

            - !If
              - NormalizaDiretorios
              - Name: Configuracoes
                ActionTypeId:
                  Category: Source
                  Owner: AWS
                  Version: "1"
                  Provider: CodeCommit
                Configuration:
                  RepositoryName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName']]
                  BranchName: config
                  PollForSourceChanges: false
                OutputArtifacts:
                  - Name: Configuracoes
                RunOrder: 1
              - !Ref AWS::NoValue
        
        - Name: Project-Structure
          Actions:
            - !If
              - NormalizaDiretorios  
              - Name: Normaliza
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                InputArtifacts:
                  - Name: Appl
                  - Name: Configuracoes
                OutputArtifacts:
                  - Name: App
                Configuration:
                  ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'NormalizaDiretorios', !Ref 'BranchName' ]]
                  PrimarySource: Configuracoes
                RunOrder: 1
              - !Ref AWS::NoValue

        - Name: Continuous-Integration
          Actions:
            - !If
              - BranchMaster
              - Name: "CriaCardJira"
                ActionTypeId:
                  Category: Invoke
                  Owner: AWS
                  Provider: Lambda
                  Version: "1"
                Configuration:
                  FunctionName: DevSecOps-CriaCardJira
                  UserParameters: !Sub /App/${FeatureName}/${MicroServiceName}/
                InputArtifacts:
                  - Name: App
                RunOrder: 1
                RoleArn: !Sub arn:aws:iam::${DevSecOpsAccount}:role/DevSecOps-LambdaExec
              - !Ref AWS::NoValue

            - Name: ControlVersion
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: ControlVersion
              InputArtifacts:
                - Name: App
                - Name: Libs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'ControlVersion', !Ref 'BranchName' ]]
                PrimarySource: Libs
              RunOrder: 1

            - Name: TestUnit
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: TestUnit
              InputArtifacts:
                - Name: App
                - Name: Libs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'TestesUnitarios', !Ref 'BranchName' ]]
                PrimarySource: App
              RunOrder: 2

            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Build
              InputArtifacts:
                - Name: App
                - Name: Libs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'Build', !Ref 'BranchName' ]]
                PrimarySource: App
              RunOrder: 2

            - Name: SonarQube
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Sonar
              InputArtifacts:
                - Name: App
                - Name: Libs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'Sonar', !Ref 'BranchName' ]]
                PrimarySource: App
              RunOrder: 2

            - Name: SAST-Fortify
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: Fortify
              InputArtifacts:
                - Name: App
                - Name: Libs
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Fortify', !Ref 'BranchName' ]]
                PrimarySource: App
              RunOrder: 2

            - Name: ContainerSecurity-Aqua
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              OutputArtifacts:
                - Name: AQUA
              InputArtifacts:
                - Name: App
                - Name: Libs
                - Name: Build
              Configuration:
                ProjectName: !Join ['-', [!Ref 'FeatureName',!Ref 'MicroServiceName', 'Aqua', !Ref 'BranchName' ]]
                PrimarySource: Libs
              RunOrder: 3

        - !If
          - BranchDevelop
          - Name: Deploy-Dev
            Actions:
              - Name: Publish
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                OutputArtifacts:
                    - Name: PublishDev
                InputArtifacts:
                    - Name: App
                    - Name: Build
                    - Name: Libs
                Configuration:
                  ProjectName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Publish-Dev' ]]
                  PrimarySource: Libs
                RunOrder: 1

              - Name: Deploy
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                OutputArtifacts:
                    - Name: DeployDev
                InputArtifacts:
                    - Name: App 
                    - Name: Build
                    - Name: Libs
                    - Name: PublishDev
                Configuration:
                  ProjectName:  !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'DeployDev', !Ref BranchName ]]
                  PrimarySource: 'Libs'
                RunOrder: 2
          - !Ref AWS::NoValue

        - !If
          - BranchMaster
          - Name: Deploy-Homolog
            Actions:
              - Name: Publish
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                OutputArtifacts:
                    - Name: PublishHomolog
                InputArtifacts:
                    - Name: App
                    - Name: Build
                    - Name: Libs
                Configuration:
                  ProjectName: !Join ['-', [!Ref 'FeatureName', !Ref 'MicroServiceName', 'Publish-Homolog' ]]
                  PrimarySource: Libs
                RunOrder: 1

              - Name: Deploy
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: "1"
                  Provider: CodeBuild
                OutputArtifacts:
                    - Name: DeployHom
                InputArtifacts:
                    - Name: App 
                    - Name: Build
                    - Name: Libs
                    - Name: PublishHomolog
                Configuration:
                  ProjectName:  !Join ['-', [!Ref 'FeatureName', 